# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       libresource

# >> macros
# << macros

Summary:    MeeGo resource management low level C API libraries
Version:    0.21.0
Release:    0
Group:      System/Resource Policy
License:    LGPLv2.1
URL:        http://meego.gitorious.org/maemo-multimedia/libresource
Source0:    maemo-multimedia-libresource-90fcf739.tar.gz
Source100:  libresource.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  pkgconfig(dbus-glib-1)
BuildRequires:  pkgconfig(check)

%description
Resource management for MeeGo. Resource policy client library.

%package client
Summary:    MeeGo resource aware client test example
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}

%description client
Resource management for MeeGo. This is a simple test tool to play with resource management.

%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Development files for %{name}.


%prep
%setup -q -n maemo-multimedia-%{name}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%autogen --disable-static
%configure --disable-static
make

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/libresource*.so.*
%doc README COPYING INSTALL AUTHORS NEWS ChangeLog
# << files

%files client
%defattr(-,root,root,-)
# >> files client
%{_bindir}/resource-client
%{_bindir}/fmradio
# << files client

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/resource*
%{_libdir}/*.so
%{_libdir}/pkgconfig/libresource*.pc
# << files devel
